### ISSUE TITLE
static ip and watchdog

### ISSUE THREAD

**Issue by iw88881111** [eg321/esp32-motorized-roller-blinds#1]
Thanks for great project and freeware it :) It's realy working in my SmartHome system (mechanical part another) for three month.
Now, I have 2 suggestions for update (discussed earlier) :
1. Abbility to assign ESP static IP address.
2. Watchdog attached to router/ip address/server etc.

Many thanks
WBR, Igor.

**Comment by eg321** [comment]
Hi!

1. Unfortunately "ESP-WiFiSettings" library does not support static IP configuration now. The best option is to request such feature there (highlighting @Juerd). Once they implement it, I'll try to use it here also.
2. There is configured watchdog already. It checks that ESP is working ok and restarting it on any issue. Another part is MQTT - there is automatic reconnection also. One thing that definitely needed to be improved is WiFi connection.
It looks like controller does not reconnect automatically to WiFi. I'll check how we can process this, but as quick workaround I've added possibility to restart board from mechanical switch with 5 clicks. It looks safe, but maybe useful in such situations.
It will be released in v2.0.1.

I'll keep open this issue for now.

**Comment by iw88881111** [comment]
Hi!
Maybe set IP/MASK in the main.cpp code? 
It's will solved bug :)

**Comment by eg321** [comment]
@iw88881111 Igor, I've implemented additional checks for WiFi connectivity. By now it uses such workflow:
1. Once WiFi is disconnected, it waits for 15 min for connection restoration.
2. Once 15 minutes is expired and still no WiFi connection is detected, device is going to restart. Timer is started again for another 15 minutes.

Please note:
1. After restart it can switch to Captive Portal mode, if no WiFi connection still detected. I don't like this, because Captive portal is public and anyone can connect to it during this period, but I cannot find better solution now.
2.  ESP8266 can restore connection immediately without reboot, but ESP32 requires reboot to properly maintain connection (so it always will wait for 15 minutes to expire and try to connect after restart).
3. Device continues handle buttons despite WiFi connection issues (even in Captive portal mode).

I've checked that at my ESP8266 and ESP32 and it works ok for me. You can check these changes at master, if you want.
Later I'll include them into the new release, if no new issues appears.

**Comment by iw88881111** [comment]
Hi!
Very well. I wil try new firmware.

**Comment by eg321** [comment]
It's not a good practice to make static IP on devices and manage them individually in the network. This should be done at DHCP server side. Almost all routers support this.

I'm closing this issue, because I believe that IP management shouldn't be a part of this device.
