### ISSUE TITLE
28BYJ-48 12v motor - how long blackout blinds it can handle? 

### ISSUE THREAD

**Issue by roulendz** [eg321/esp32-motorized-roller-blinds#18]
For what blind lengths other people use 28BYJ-48 12v?

Because I have 2.4m long blackout blinds, and wondering if it will work. 🤔

Thank you.

**Comment by eg321** [comment]
Hi,

I'm using 28BYJ-48 12v  for ~1.5m blackout blinds more than 2 years. It's ok for this size. If torque will be not enough, you can configure speed (smaller speed - more torque) - firmware allows that. It's not a big difference to open blind in 1 minute or 2 minutes for me, because I'm opening it automatically by HA each morning.

It will be great, if someone else share their experience.
