### ISSUE TITLE
turn motor speed (variable)

### ISSUE THREAD

**Issue by iw88881111** [eg321/esp32-motorized-roller-blinds#2]
In testing, when blinds have more length 28byj can not up it.
I change variable "motor speed" to low level (10) and motor worked. 
Maybe turn this variable to configuration page.

Thanks.
WBR, Igor.

**Comment by eg321** [comment]
Hi,
this implemented in upcoming 2.0 release actually (https://github.com/eg321/esp32-motorized-roller-blinds/commit/51b5972f9db950abd98cf94e50142fe9b9b4165b).
It will allow to change main settings (including motors and pins) at captive portal (yeah, wipe is needed). So, no needs to rebuild your own firmware, because all settings will be stored at FS.
30 RPM by default, but you can decrease it now.
Also, I've added support of 4 motors out of the box.

I'm going to publish it soon, but you already can check it up from master.

Thanks for the issue!

**Comment by eg321** [comment]
2.0 is released today: https://github.com/eg321/esp32-motorized-roller-blinds/releases/tag/v2.0

Closing the issue. Feel free to reopen if still actually.

**Comment by iw88881111** [comment]
Hi!
1. After uploaded new firmware to ESP32, -  I set stepper speed (RPM) to "10" and blinds really turn slowlk. But after wipe setting from WEB interface it is backing to faster than "10" (I think "30"), even if I set it slowly ("10") in config portal .
Maybe RPM config not saved/loaded correctly?
2. I mean settings for steppers pins in config portal more correctclty named "GPIO NUMBER" not "PIN NUMBER".
3. Not very imporrtant: make RPM setting for each steppers separatly.
