### ISSUE TITLE
folder.ino 

### ISSUE THREAD

**Issue by tiruds76** [eg321/esp32-motorized-roller-blinds#20]
Hello I start with Arduino and I don't understand how to add the code? I can't find a.ino file in your folder

**Comment by eg321** [comment]
Hi!
This project was developed in Platformio: https://platformio.org/
You can try to install it and open this project. All dependencies will be installed automatically. 

I can't keep this issue open, because it's not related to the project. I believe you'll find assistance at Platformio related resources.
Will be glad to see you again with Platformio and successful compilation of this project.
Good luck!
